export const env = {
	REGISTER_USER_ENDPOINT: import.meta.env.VITE_API_REGISTER_USER_ENDPOINT,
	UPDATE_USER_ENDPOINT: import.meta.env.VITE_API_UPDATE_USER_ENDPOINT,
	DISABLE_USER_ENDPOINT: import.meta.env.VITE_API_TOGGLE_DISABLE_USER_ENDPOINT,
};
